### ISSUE TITLE
SINTESIS

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Litzy-lopez4#1]
[SINTESIS_U2_LitzyLopezLopez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Litzy-lopez4/files/12704359/SINTESIS_U2_LitzyLopezLopez.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
